name: Push commit

on:
  push:
    branches: [main, master]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Donnie Musgrove'
          git config --global user.email 'donaldmusgrove@users.noreply.github.com'
          git commit -am "Automated report"
          git push
