name: Push commit

on:
  push:
    branches: [main, master]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email 'donaldmusgrove@users.noreply.github.com'
          git add report.txt
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
