name: Render README

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      # Install packages needed
      - name: install required packages
        run: Rscript -e 'install.packages("rmarkdown")'

      # Render README.md using rmarkdown
      - name: render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit README
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email 'donaldmusgrove@users.noreply.github.com'
          git add README.md
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
